development:
  adapter: mysql2
  database: enterprise_site_development
  host: 127.0.0.1
  username: root
  password: "123456"
  pool: 5
  encoding: utf8

development:
  adapter: mysql2
  database: enterprise_site_test
  host: 127.0.0.1
  username: root
  password: "123456"
  pool: 5
  encoding: utf8

production:
  adapter: mysql2
  database: enterprise_site_production
  username: root
  password: "123456"
  pool: 5

